pipeline {
    agent any

    environment {
        git_branch = 'main'
        git_url = 'git@github.com:maruthibg1998/demo2.git'
    }

    stages {

        stage('Clone') {
            steps {
                git branch: "${git_branch}", url: "${git_url}"
            }
        }

        stage('Compile') {
            steps {
                dir('maruthi') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('maruthi') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('maruthi') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
